Card Store/Controllers/YugiohController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Card_Store.Models;

namespace Card_Store.Controllers
{
    public class YugiohController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.obeliskTheTormentor = new Pokemon
            {
                Name = "Obelisk the Tormentor",
                Rarety = "Ultra Rare",
                MarketPrice = 1.21,
                ImagePath = "/Content/Images/obeliskTheTormentor.jpg"
            };

            ViewBag.sliferTheSkyDragon = new Pokemon
            {
                Name = "Slifer the Sky Dragon",
                Rarety = "Ultra Rare",
                MarketPrice = 1.14,
                ImagePath = "/Content/Images/sliferTheSkyDragon.jpg"
            };

            ViewBag.knightmarePhoenix = new Pokemon
            {
                Name = "Knightmare Phoenix",
                Rarety = "Rare",
                MarketPrice = 0.57,
                ImagePath = "/Content/Images/knightmarePhoenix.jpg"
            };

            ViewBag.soulCrossing = new Pokemon
            {
                Name = "Soul Crossing",
                Rarety = "Ultra Rare",
                MarketPrice = 1.19,
                ImagePath = "/Content/Images/soulCrossing.jpg"
            };

            ViewBag.skullMeister = new Pokemon
            {
                Name = "Skull Meister",
                Rarety = "Rare",
                MarketPrice = 0.81,
                ImagePath = "/Content/Images/skullMeister.jpg"
            };

            ViewBag.swapFrog = new Pokemon
            {
                Name = "Swap Frog",
                Rarety = "Ultra Rare",
                MarketPrice = 1.99,
                ImagePath = "/Content/Images/swapFrog.jpg"
            };

            return View();
        }
    }
}

Card Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="navbar navbar-fixed-top">
        <a href="/Home/Index">
            <img src="~/Content/Images/logo.jpg">
        </a>
        <div class="container main-navbar">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Magic", "Index", "Magic")</li>
                    <li>@Html.ActionLink("Yu-Gi-Oh!", "Index", "Yugioh")</li>
                    <li>@Html.ActionLink("Pokemon", "Index", "Pokemon")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <ul class="nav navbar-nav footer-navbar">
                <li>@Html.ActionLink("Magic", "Index", "Magic")</li>
                <li>@Html.ActionLink("Yu-Gi-Oh!", "Index", "Yugioh")</li>
                <li>@Html.ActionLink("Pokemon", "Index", "Pokemon")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="copyright">&copy; @DateTime.Now.Year - Card Store</li>
            </ul>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>